(function(){
'use strict';

const CFG = window.FACTURA_FIREBASE_CONFIG || {enabled:false, companyId:'aw', companyDefaults:{}};
const COMPANY = CFG.companyId || 'aw';
const NAV = [
 ['dashboard','Inicio','🏠'], ['orders','Pedidos','📦'], ['invoices','Facturas','🧾'], ['purchases','Compras','🛒'],
 ['stock','Stock','🏬'], ['stores','Tiendas','🏪'], ['wastage','Mermas','🗑️'], ['clients','Clientes','👥'],
 ['products','Productos','🥭'], ['suppliers','Proveedores','🚛'], ['expenses','Gastos','💶'], ['payments','Cobros','✅'],
 ['reports','Informes','📊'], ['settings','Ajustes','⚙️']
];
const DEF_PRODUCTS = [
 {code:'MV',name:'MACHO VERDE',aliases:['verde','platano verde','plátano verde'],mode:'box_kg',kgBox:22,vat:4,buy:1.05,sell:1.25,margin:18,unit:'kg'},
 {code:'MM',name:'MACHO MADURO',aliases:['maduro','platano maduro','plátano maduro'],mode:'box_kg',kgBox:22,vat:4,buy:1.50,sell:1.70,margin:18,unit:'kg'},
 {code:'YU',name:'YUCA',aliases:['yuca'],mode:'box_kg',kgBox:18,vat:4,buy:1.70,sell:1.95,margin:18,unit:'kg'},
 {code:'GV',name:'GUINEO VERDE',aliases:['guineo'],mode:'box_kg',kgBox:18,vat:4,buy:1.20,sell:1.45,margin:18,unit:'kg'},
 {code:'BN',name:'BANANA',aliases:['banana'],mode:'kg',kgBox:0,vat:4,buy:1.00,sell:1.25,margin:20,unit:'kg'},
 {code:'AP',name:'AGUACATE PRIMERA',aliases:['aguacate primera'],mode:'box_fixed',kgBox:0,vat:4,buy:18,sell:19.5,margin:12,unit:'caja'},
 {code:'AV',name:'AVOCADO',aliases:['aguacate tropical','avocado'],mode:'box_fixed',kgBox:0,vat:4,buy:20.40,sell:25,margin:18,unit:'caja'},
 {code:'TD',name:'TOMATE DANIELA',aliases:['daniela','tomate'],mode:'kg',kgBox:0,vat:4,buy:1.70,sell:2.29,margin:20,unit:'kg'},
 {code:'MG',name:'MANGO',aliases:['mango'],mode:'box_fixed',kgBox:0,vat:4,buy:8,sell:10,margin:20,unit:'caja'},
 {code:'LX',name:'LIMON EXTRA',aliases:['limon extra','limón extra'],mode:'box_fixed',kgBox:0,vat:4,buy:10,sell:12,margin:18,unit:'caja'},
 {code:'LM',name:'LIMA',aliases:['lima'],mode:'box_fixed',kgBox:0,vat:4,buy:10,sell:12,margin:18,unit:'caja'},
 {code:'CL',name:'CILANTRO',aliases:['cilantro'],mode:'unit',kgBox:0,vat:10,buy:0.40,sell:0.60,margin:35,unit:'manojo'},
 {code:'OK',name:'OKRA',aliases:['ocra','okra'],mode:'box_fixed',kgBox:0,vat:4,buy:27,sell:29,margin:12,unit:'caja'},
 {code:'HB',name:'HABANERO',aliases:['habanero'],mode:'box_fixed',kgBox:0,vat:10,buy:15,sell:18,margin:18,unit:'caja'},
 {code:'AJ',name:'AJO PRIMERA',aliases:['ajo','ajo primera'],mode:'kg',kgBox:0,vat:10,buy:3.50,sell:4.00,margin:18,unit:'kg'},
 {code:'GD',name:'GUINDILLA',aliases:['gundeya','guindilla'],mode:'kg',kgBox:0,vat:10,buy:4.50,sell:5.80,margin:20,unit:'kg'},
 {code:'JG',name:'JENGIBRE',aliases:['jengibre'],mode:'kg',kgBox:0,vat:10,buy:2.50,sell:2.75,margin:20,unit:'kg'}
];
const DEF_CLIENTS = [
 {id:'adnan',name:'Adnan Asif',nif:'X7128589S',address:'C/ Padre Flórez 3, Burgos',transport:0,commission:15},
 {id:'abbas',name:'ABBAS',transport:10,commission:0}, {id:'nadeem',name:'NADEEM',transport:10,commission:0},
 {id:'dani',name:'DANI',transport:10,commission:0}, {id:'romina',name:'ROMINA-PREMIER',transport:10,commission:0}
];
let fb={app:null,auth:null,db:null}, user=null, companyRef=null, cloud=false;
let state={settings:{},products:{},clients:{},suppliers:{},orders:{},purchases:{},invoices:{},storeTransfers:{},wastage:{},expenses:{},payments:{},stores:{'san-pablo':{name:'San Pablo'},'san-lesmes':{name:'San Lesmes'},'santiago':{name:'Santiago'}},auditLog:{}};
let view='dashboard', draftInv=null, draftPur=null, draftOrd=null, editInv=null, editPur=null;
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const uid=(p='id')=>p+'_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,7);
const now=()=>Date.now(); const today=()=>new Date().toISOString().slice(0,10);
function norm(s){return String(s||'').toUpperCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^A-Z0-9]+/g,' ').trim();}
function slug(s){return norm(s).toLowerCase().replace(/\s+/g,'-')||uid('x')}
function n(v){ if(v==null)return 0; let s=String(v).trim().replace(/\s/g,''); if(!s)return 0; let c=s.lastIndexOf(','), d=s.lastIndexOf('.'); if(c>-1&&d>-1){s=c>d?s.replace(/\./g,'').replace(',','.'):s.replace(/,/g,'')} else s=s.replace(',','.'); const x=Number(s); return Number.isFinite(x)?x:0;}
function r2(x){return Math.round((Number(x)||0)*100)/100} function money(x){return (Number(x)||0).toLocaleString('es-ES',{minimumFractionDigits:2,maximumFractionDigits:2})+' €'} function q(x,d=2){return (Number(x)||0).toLocaleString('es-ES',{maximumFractionDigits:d})} function fd(iso){if(!iso)return'';let[a,b,c]=iso.split('-');return `${c}/${b}/${a}`}
function recPrice(cost,margin){cost=n(cost);margin=n(margin); if(!cost)return 0; if(margin<=0||margin>=95)return cost; return r2(cost/(1-margin/100));}
function initDefaults(){
 if(!state.settings||!state.settings.name) state.settings={name:'FACTURA AW',companyName:CFG.companyDefaults.companyName,nif:CFG.companyDefaults.nif,address:CFG.companyDefaults.address,phone:CFG.companyDefaults.phone,email:CFG.companyDefaults.email,theme:'light',pin:'1234',prefix:'FA',year:new Date().getFullYear(),next:1,syncProducts:true,protectIssued:true};
 if(!state.products||!Object.keys(state.products).length){state.products={}; DEF_PRODUCTS.forEach(p=>{let id=slug(p.name); state.products[id]={id,code:p.code,name:p.name,aliases:p.aliases||[],mode:p.mode,kgBox:p.kgBox,vat:p.vat,buy:p.buy,sell:p.sell,margin:p.margin,unit:p.unit,clientMin:{},clientPrice:{},active:true}})}
 if(!state.clients||!Object.keys(state.clients).length){state.clients={}; DEF_CLIENTS.forEach(c=>{let id=c.id||slug(c.name); state.clients[id]={id,name:c.name,nif:c.nif||'',address:c.address||'',transport:c.transport||0,commission:c.commission||0,active:true}})}
 if(!state.stores)state.stores={'san-pablo':{name:'San Pablo'},'san-lesmes':{name:'San Lesmes'},'santiago':{name:'Santiago'}};
}
function products(){return Object.values(state.products||{}).sort((a,b)=>(a.code||a.name).localeCompare(b.code||b.name))} function clients(){return Object.values(state.clients||{}).sort((a,b)=>a.name.localeCompare(b.name))} function suppliers(){return Object.values(state.suppliers||{}).sort((a,b)=>a.name.localeCompare(b.name))}
function findProduct(x){let y=norm(x).replace(/\s/g,''); if(!y)return null; for(const p of products()) if(norm(p.code).replace(/\s/g,'')===y) return p; let z=norm(x); for(const p of products()){let arr=[p.name,p.code,...(p.aliases||[])].map(norm); if(arr.includes(z))return p} for(const p of products()){let hay=[p.name,p.code,...(p.aliases||[])].map(norm).join(' '); if(hay.includes(z))return p} return null}
function productDefaults(p,clientId=''){let rp=recPrice(p.buy,p.margin||18), min=n(p.clientMin?.[clientId]), cp=n(p.clientPrice?.[clientId]); return {productId:p.id,code:p.code,name:p.name,mode:p.mode||'kg',kgBox:n(p.kgBox),vat:n(p.vat||4),buy:n(p.buy),sell:n(cp||min||p.sell||rp),recommended:rp,minClient:min,unit:p.unit||'kg'}}
function line(){return {id:uid('l'),productId:'',code:'',name:'',mode:'kg',qty:'',kgBox:'',gross:'',tare:'',price:'',vat:4,buy:0,recommended:0,minClient:0,manual:false}}
function lines(count=8){let o={}; for(let i=0;i<count;i++){let l=line();o[l.id]=l}return o}
function applyProduct(l,query,clientId='',purchase=false){let p=findProduct(query); if(!p)return {...l,name:query,code:'',productId:''}; let d=productDefaults(p,clientId); return {...l,productId:p.id,code:d.code,name:d.name,mode:d.mode,kgBox:d.kgBox||'',vat:d.vat,buy:d.buy,recommended:d.recommended,minClient:d.minClient,price:purchase?d.buy:(l.manual?l.price:d.sell)}}
function amount(l,purchase=false){let mode=l.mode||'kg', qty=n(l.qty), kg=n(l.kgBox), gross=n(l.gross), tare=n(l.tare), price=purchase?n(l.price||l.buy):n(l.price); let baseQty=0; if(mode==='kg')baseQty=Math.max(0,(gross||qty)-tare); else if(mode==='box_kg')baseQty=qty*kg; else baseQty=qty; let base=r2(baseQty*price), tax=r2(base*n(l.vat)/100); return {baseQty:r2(baseQty),base,tax,total:r2(base+tax)}}
function invTotals(inv){let sub=0,tax=0,types=new Set(); Object.values(inv.lines||{}).forEach(l=>{let a=amount(l,false); sub+=a.base; tax+=a.tax; if(a.base)types.add(n(l.vat))}); let transport=r2(sub*n(inv.transport)/100+n(inv.transportManual)); let tv=n(inv.transportVat); if(transport&&tv){tax+=r2(transport*tv/100);types.add(tv)} let base=r2(sub+transport), total=r2(base+tax), paid=n(inv.paid); return {sub:r2(sub),transport,base,tax:r2(tax),total,paid,pending:r2(total-paid),types:[...types].sort((a,b)=>a-b)}}
function purTotals(pur){let sub=0,tax=0; Object.values(pur.lines||{}).forEach(l=>{let a=amount(l,true); sub+=a.base; tax+=a.tax}); return {sub:r2(sub),tax:r2(tax),total:r2(sub+tax)}}
async function setPath(path,val){ if(cloud&&companyRef)return companyRef.child(path).set(val); let a=path.split('/'),o=state; while(a.length>1){let k=a.shift();o[k]=o[k]||{};o=o[k]} o[a[0]]=val; localStorage.setItem('factura_aw_local',JSON.stringify(state)); render() }
async function update(paths){ if(cloud&&companyRef)return companyRef.update(paths); Object.entries(paths).forEach(([p,v])=>{let a=p.split('/'),o=state; while(a.length>1){let k=a.shift();o[k]=o[k]||{};o=o[k]} if(v===null)delete o[a[0]]; else o[a[0]]=v}); localStorage.setItem('factura_aw_local',JSON.stringify(state)); render() }
function status(t,ok=true){$('#status').textContent=t; $('#status').style.color=ok?'var(--muted)':'var(--danger)'} function title(t){$('#title').textContent=t}
function openDlg(html){$('#dlgBody').innerHTML=html; $('#dlg').showModal()} function err(m){openDlg(`<div class="notice bad">${esc(m)}</div>`)}
function applyTheme(){let th=state.settings?.theme||localStorage.getItem('theme')||'light'; document.body.classList.toggle('dark',th==='dark'); $('#theme').textContent=th==='dark'?'Modo blanco':'Modo negro'}
function nav(){ $('#nav').innerHTML=NAV.map(([k,l,i])=>`<button data-v="${k}" class="${view===k?'active':''}"><span>${i}</span><span>${l}</span></button>`).join(''); $$('#nav button').forEach(b=>b.onclick=()=>{view=b.dataset.v; $('#side').classList.remove('open'); render()})}
function lists(){ $('#productList').innerHTML=products().map(p=>`<option value="${esc(p.code)}">${esc(p.name)}</option><option value="${esc(p.name)}">${esc(p.code)}</option>`).join(''); $('#clientList').innerHTML=clients().map(c=>`<option value="${esc(c.name)}"></option>`).join(''); $('#supplierList').innerHTML=suppliers().map(s=>`<option value="${esc(s.name)}"></option>`).join('') }
async function initFirebase(){ if(!CFG.enabled){let raw=localStorage.getItem('factura_aw_local'); if(raw)state=JSON.parse(raw); initDefaults(); $('#shell').classList.remove('hidden'); status('Modo local'); render(); return} try{firebase.initializeApp(CFG.firebaseConfig); fb.auth=firebase.auth(); fb.db=firebase.database(); fb.auth.onAuthStateChanged(async u=>{user=u; if(!u){$('#login').classList.remove('hidden'); $('#shell').classList.add('hidden'); return} $('#login').classList.add('hidden'); $('#shell').classList.remove('hidden'); await bootstrap(u); subscribe()})}catch(e){err(e.message);status('Error Firebase',false)} }
async function bootstrap(u){try{let ok=await fb.db.ref(`userCompanies/${u.uid}/${COMPANY}`).get(); if(ok.exists())return}catch(e){} try{let users=await fb.db.ref(`companies/${COMPANY}/users`).get(); if(!users.exists()){let seed={settings:{name:'FACTURA AW',companyName:CFG.companyDefaults.companyName,nif:CFG.companyDefaults.nif,address:CFG.companyDefaults.address,phone:CFG.companyDefaults.phone,email:CFG.companyDefaults.email,theme:'light',pin:'1234',prefix:'FA',year:new Date().getFullYear(),next:1,syncProducts:true,protectIssued:true},users:{[u.uid]:{email:u.email,name:u.email.split('@')[0],role:'admin',active:true}},products:{},clients:{},suppliers:{},orders:{},purchases:{},invoices:{},storeTransfers:{},wastage:{},expenses:{},payments:{},stores:{'san-pablo':{name:'San Pablo'},'san-lesmes':{name:'San Lesmes'},'santiago':{name:'Santiago'}},auditLog:{}}; DEF_PRODUCTS.forEach(p=>{let id=slug(p.name);seed.products[id]={id,code:p.code,name:p.name,aliases:p.aliases,mode:p.mode,kgBox:p.kgBox,vat:p.vat,buy:p.buy,sell:p.sell,margin:p.margin,unit:p.unit,clientMin:{},clientPrice:{},active:true}}); DEF_CLIENTS.forEach(c=>{let id=c.id;seed.clients[id]={id,name:c.name,nif:c.nif||'',address:c.address||'',transport:c.transport||0,commission:c.commission||0,active:true}}); await fb.db.ref(`companies/${COMPANY}`).set(seed); await fb.db.ref(`userCompanies/${u.uid}/${COMPANY}`).set(true)}}catch(e){console.warn(e)} }
function subscribe(){companyRef=fb.db.ref(`companies/${COMPANY}`); companyRef.on('value',s=>{state=s.val()||{}; initDefaults(); cloud=true; status('Cloud sincronizado · '+user.email); render()},e=>{status('Permiso denegado',false);err('Revisa reglas, UID y userCompanies: '+e.message)})}
function render(){initDefaults();applyTheme();lists();nav(); let f={dashboard,productsView,clientsView,suppliersView,invoicesView,purchasesView,ordersView,stockView,storesView,wastageView,expensesView,paymentsView,reportsView,settingsView}[view]||dashboard; f()}
function kpi(l,v,s=''){return `<div class="card"><div class="muted">${l}</div><div class="kpi">${v}</div><small class="muted">${s}</small></div>`}
function table(h,rows){return `<div class="tablewrap"><table><thead><tr>${h.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${h.length}" class="muted">Sin datos</td></tr>`}</tbody></table></div>`}
function stockCalc(){let s={}; function ens(l){let c=l.code||'SIN'; if(!s[c])s[c]={code:c,name:l.name||c,in:0,sold:0,store:0,waste:0,value:0,purchases:[],sales:[]}; return s[c]}
 Object.values(state.purchases||{}).forEach(p=>{if(p.status==='cancelled')return; Object.values(p.lines||{}).forEach(l=>{let a=amount(l,true),x=ens(l);x.in+=a.baseQty;x.value+=a.base;x.purchases.push({date:p.date,who:p.supplierName,qty:a.baseQty,price:n(l.price),total:a.base})})});
 Object.values(state.invoices||{}).forEach(i=>{if(['annulled','cancelled'].includes(i.status))return; Object.values(i.lines||{}).forEach(l=>{let a=amount(l,false),x=ens(l);x.sold+=a.baseQty;x.sales.push({date:i.date,who:i.clientName,number:i.number,qty:a.baseQty,price:n(l.price),total:a.base})})});
 Object.values(state.storeTransfers||{}).forEach(t=>Object.values(t.lines||{}).forEach(l=>{let a=amount({...l,price:l.buy||l.price},false),x=ens(l);x.store+=a.baseQty}));
 Object.values(state.wastage||{}).forEach(w=>Object.values(w.lines||{}).forEach(l=>{let a=amount({...l,price:l.buy||l.price},false),x=ens(l);x.waste+=a.baseQty}));
 Object.values(s).forEach(x=>{x.avg=x.in?x.value/x.in:0;x.qty=r2(x.in-x.sold-x.store-x.waste);x.stockValue=r2(x.qty*x.avg)}); return s}
function dashboard(){title('Inicio');let sales=0,buys=0,pending=0;Object.values(state.invoices||{}).forEach(i=>{let t=invTotals(i);if(!['annulled','cancelled'].includes(i.status)){sales+=t.total;pending+=t.pending}});Object.values(state.purchases||{}).forEach(p=>{if(p.status!=='cancelled')buys+=purTotals(p).total});let st=stockCalc(),sv=Object.values(st).reduce((a,x)=>a+x.stockValue,0);let exp=Object.values(state.expenses||{}).reduce((a,e)=>a+n(e.amount),0);$('#view').innerHTML=`<div class="grid cards">${kpi('Ventas',money(sales))}${kpi('Compras',money(buys))}${kpi('Stock €',money(sv))}${kpi('Resultado comercial',money(sales+sv-buys-exp))}</div><div class="card"><h3>Acciones rápidas</h3><div class="row"><button class="btn primary" onclick="window.awGo('invoices')">Nueva factura</button><button class="btn" onclick="window.awGo('purchases')">Nueva compra</button><button class="btn" onclick="window.awGo('orders')">Pegar pedido</button><button class="btn" onclick="window.awGo('settings')">Limpiar ventas</button></div></div>`}
window.awGo=v=>{view=v;render()}
function lineRows(doc,type){let purchase=type==='purchase';return `<div class="desktopLines tablewrap"><table class="lines"><thead><tr><th>Cód.</th><th>Producto</th><th>Modo</th><th>Cant.</th><th>Kg/caja</th><th>Bruto kg</th><th>Tara kg</th><th>${purchase?'Compra':'Venta'}</th>${!purchase?'<th>Recom.</th><th>Mín.</th>':''}<th>IVA</th><th>Base</th><th></th></tr></thead><tbody>${Object.values(doc.lines||{}).map(l=>row(l,type)).join('')}</tbody></table></div><div class="mobileLines">${Object.values(doc.lines||{}).map(l=>cardLine(l,type)).join('')}</div>`}
function modeOptions(m){return ['kg','box_kg','box_fixed','unit'].map(x=>`<option value="${x}" ${m===x?'selected':''}>${{kg:'Kg',box_kg:'Caja x kg',box_fixed:'Caja fija',unit:'Ud/Manojo'}[x]}</option>`).join('')}
function row(l,type){let a=amount(l,type==='purchase'),p=type==='purchase';return `<tr data-id="${l.id}"><td><input class="code" value="${esc(l.code)}" placeholder="MV"></td><td><input class="name prod" list="productList" value="${esc(l.name)}" placeholder="Nombre completo"></td><td><select class="mode">${modeOptions(l.mode)}</select></td><td><input class="qty" inputmode="decimal" value="${esc(l.qty)}" placeholder="cant."></td><td><input class="kg" inputmode="decimal" value="${esc(l.kgBox)}" placeholder="kg/caja"></td><td><input class="gross" inputmode="decimal" value="${esc(l.gross)}" placeholder="kg bruto"></td><td><input class="tare" inputmode="decimal" value="${esc(l.tare)}" placeholder="tara kg"></td><td><div class="priceBtns"><button class="btn mini down">-0,10</button><input class="price" inputmode="decimal" value="${esc(l.price)}" placeholder="€"><button class="btn mini up">+0,10</button></div></td>${!p?`<td><button class="btn mini rec">${money(l.recommended||0)}</button></td><td><button class="btn mini min">${l.minClient?money(l.minClient):'—'}</button></td>`:''}<td><select class="vat">${[0,4,10,21].map(v=>`<option value="${v}" ${n(l.vat)===v?'selected':''}>${v}%</option>`).join('')}</select></td><td><b>${money(a.base)}</b><br><small class="muted">${q(a.baseQty)} kg/ud</small></td><td><button class="btn mini del">×</button></td></tr>`}
function cardLine(l,type){let a=amount(l,type==='purchase'),p=type==='purchase';return `<div class="linecard" data-id="${l.id}"><div class="row between"><b>${esc(l.code||'Línea')}</b><button class="btn mini del">Eliminar</button></div><div class="mini"><label>Cód.<input class="code" value="${esc(l.code)}" placeholder="MV"></label><label>Producto<input class="name" list="productList" value="${esc(l.name)}" placeholder="Producto"></label><label>Modo<select class="mode">${modeOptions(l.mode)}</select></label><label>Cant.<input class="qty" inputmode="decimal" value="${esc(l.qty)}" placeholder="cant."></label><label>Kg/caja<input class="kg" inputmode="decimal" value="${esc(l.kgBox)}" placeholder="kg/caja"></label><label>Bruto kg<input class="gross" inputmode="decimal" value="${esc(l.gross)}" placeholder="kg bruto"></label><label>Tara kg<input class="tare" inputmode="decimal" value="${esc(l.tare)}" placeholder="tara kg"></label><label>Precio<input class="price" inputmode="decimal" value="${esc(l.price)}" placeholder="€"></label><label>IVA<select class="vat">${[0,4,10,21].map(v=>`<option value="${v}" ${n(l.vat)===v?'selected':''}>${v}%</option>`).join('')}</select></label></div><div class="row"><button class="btn mini down">-0,10</button><button class="btn mini up">+0,10</button>${!p?`<button class="btn mini rec">Recom. ${money(l.recommended||0)}</button><button class="btn mini min">Mín. ${l.minClient?money(l.minClient):'—'}</button>`:''}<span class="badge">Base ${money(a.base)}</span></div></div>`}
function bindLines(doc,type,redraw){let purchase=type==='purchase';$$('[data-id]').forEach(el=>{let id=el.dataset.id,l=doc.lines[id]; if(!l)return; let get=c=>el.querySelector(c); get('.code').onchange=()=>{doc.lines[id]=applyProduct(l,get('.code').value,doc.clientId,purchase);redraw()}; get('.name').onchange=()=>{doc.lines[id]=applyProduct(l,get('.name').value,doc.clientId,purchase);redraw()}; get('.name').oninput=()=>{doc.lines[id].name=get('.name').value}; get('.code').oninput=()=>{doc.lines[id].code=get('.code').value}; get('.mode').onchange=()=>{doc.lines[id].mode=get('.mode').value;redraw()}; ['qty','kg','gross','tare','price'].forEach(cls=>{get('.'+cls).oninput=()=>{let key={kg:'kgBox'}[cls]||cls; doc.lines[id][key]=get('.'+cls).value; if(cls==='price')doc.lines[id].manual=true}; get('.'+cls).onblur=()=>redraw()}); get('.vat').onchange=()=>{doc.lines[id].vat=n(get('.vat').value);redraw()}; get('.up').onclick=()=>{doc.lines[id].price=r2(n(doc.lines[id].price)+.10);doc.lines[id].manual=true;redraw()}; get('.down').onclick=()=>{doc.lines[id].price=r2(n(doc.lines[id].price)-.10);doc.lines[id].manual=true;redraw()}; get('.del').onclick=()=>{delete doc.lines[id];redraw()}; let rec=get('.rec'); if(rec)rec.onclick=()=>{doc.lines[id].price=doc.lines[id].recommended||doc.lines[id].price;doc.lines[id].manual=false;redraw()}; let min=get('.min'); if(min)min.onclick=()=>{if(doc.lines[id].minClient){doc.lines[id].price=doc.lines[id].minClient;doc.lines[id].manual=false;redraw()}}})}
function summary(t,invoice=false){return `<div class="summary"><div class="sumBox"><div class="sumLine"><span>Subtotal productos</span><b>${money(t.sub||t.subtotal||0)}</b></div>${t.transport?`<div class="sumLine"><span>Transporte</span><b>${money(t.transport)}</b></div>`:''}<div class="sumLine"><span>Base imponible</span><b>${money(t.base||t.sub||0)}</b></div><div class="sumLine"><span>IVA total</span><b>${money(t.tax)}</b></div>${invoice?`<div class="sumLine"><span>IVA aplicado</span><b>${t.types?.length?t.types.join('% / ')+'%':'—'}</b></div>`:''}<div class="totalBox"><small>Total</small><strong>${money(t.total)}</strong>${invoice?`<span class="muted">Pendiente ${money(t.pending)}</span>`:''}</div></div></div>`}
function newInv(){return {id:uid('inv'),number:nextNo(),date:today(),clientId:'',clientName:'',status:'draft',transport:0,transportManual:0,transportVat:0,paid:0,lines:lines(8),createdAt:now()}} function nextNo(){return `${state.settings.prefix||'FA'}-${state.settings.year||new Date().getFullYear()}-${String(state.settings.next||1).padStart(6,'0')}`}
function invoicesView(){title('Facturas'); if(!draftInv)draftInv=newInv(); let t=invTotals(draftInv); $('#view').innerHTML=`<div class="card"><div class="row between"><h3>${editInv?'Editar/Reabrir':'Nueva factura'}</h3><div class="row"><button id="newInv" class="btn">Nueva limpia</button><button id="addInv" class="btn">+5 líneas</button><button id="pasteInv" class="btn">Pegar pedido</button></div></div><div class="form"><label>Cliente<input id="iClient" list="clientList" value="${esc(draftInv.clientName)}" placeholder="Cliente"></label><label>Fecha<input id="iDate" type="date" value="${draftInv.date}"></label><label>Nº<input id="iNo" value="${esc(draftInv.number)}"></label><label>Estado<select id="iStatus">${['draft','issued','paid','partial','reopened','annulled'].map(s=>`<option ${draftInv.status===s?'selected':''}>${s}</option>`).join('')}</select></label><label>Transporte %<input id="iTransport" inputmode="decimal" value="${draftInv.transport}"></label><label>Transporte manual<input id="iTransM" inputmode="decimal" value="${draftInv.transportManual||''}"></label><label>IVA transporte<select id="iTransVat">${[0,4,10,21].map(v=>`<option value="${v}" ${n(draftInv.transportVat)===v?'selected':''}>${v}%</option>`).join('')}</select></label><label>Cobrado<input id="iPaid" inputmode="decimal" value="${draftInv.paid||''}"></label></div><div class="notice" style="margin:12px 0">Los campos muestran ayudas: kg, kg/caja, kg bruto y tara kg. El precio recomendado sale según coste de compra y margen objetivo. Siempre puedes modificar manualmente.</div>${lineRows(draftInv,'invoice')}${summary(t,true)}<div class="row" style="margin-top:12px"><button id="saveDraft" class="btn">Guardar borrador</button><button id="issue" class="btn primary">Emitir/guardar</button><button id="pdf" class="btn">PDF cliente</button><button id="cancelEdit" class="btn">Cancelar edición</button></div></div><div class="card"><h3>Facturas guardadas</h3>${table(['Fecha','Nº','Cliente','Total','Estado','Acciones'],Object.values(state.invoices||{}).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0)).map(i=>{let tt=invTotals(i);return [fd(i.date),esc(i.number),esc(i.clientName),money(tt.total),`<span class="badge ${i.status==='paid'?'ok':i.status==='annulled'?'bad':'warn'}">${i.status}</span>`,`<button class="btn mini" data-open="${i.id}">Abrir/Reabrir</button> <button class="btn mini" data-pdf="${i.id}">PDF</button> <button class="btn mini" data-dup="${i.id}">Duplicar</button>`]}))}</div>`; bindInvoice()}
function bindInvoice(){let d=draftInv, redraw=invoicesView; $('#newInv').onclick=()=>{if(confirm('¿Vaciar factura actual?')){editInv=null;draftInv=newInv();redraw()}}; $('#addInv').onclick=()=>{for(let i=0;i<5;i++){let l=line();d.lines[l.id]=l}redraw()}; $('#pasteInv').onclick=()=>pasteModal('invoice'); $('#iClient').oninput=()=>d.clientName=$('#iClient').value; $('#iClient').onchange=()=>{let c=clients().find(x=>norm(x.name)===norm($('#iClient').value)); d.clientName=$('#iClient').value; if(c){d.clientId=c.id;d.clientName=c.name;d.transport=c.transport||0} Object.values(d.lines).forEach(l=>{if(l.productId){let p=state.products[l.productId],def=productDefaults(p,d.clientId);l.recommended=def.recommended;l.minClient=def.minClient;if(!l.manual)l.price=def.sell}});redraw()}; ['iDate','iNo','iStatus','iTransport','iTransM','iTransVat','iPaid'].forEach(id=>{$('#'+id).oninput=()=>{let m={iDate:'date',iNo:'number',iStatus:'status',iTransport:'transport',iTransM:'transportManual',iTransVat:'transportVat',iPaid:'paid'};d[m[id]]=$('#'+id).value}; $('#'+id).onblur=()=>redraw()}); bindLines(d,'invoice',redraw); $('#saveDraft').onclick=()=>saveInv('draft'); $('#issue').onclick=()=>saveInv('issued'); $('#pdf').onclick=()=>pdfInvoice(d); $('#cancelEdit').onclick=()=>{editInv=null;draftInv=newInv();redraw()}; $$('[data-open]').forEach(b=>b.onclick=()=>{editInv=b.dataset.open;draftInv=JSON.parse(JSON.stringify(state.invoices[editInv])); if(draftInv.status==='issued')draftInv.status='reopened'; redraw()}); $$('[data-pdf]').forEach(b=>b.onclick=()=>pdfInvoice(state.invoices[b.dataset.pdf])); $$('[data-dup]').forEach(b=>b.onclick=()=>{let x=JSON.parse(JSON.stringify(state.invoices[b.dataset.dup]));x.id=uid('inv');x.number=nextNo();x.status='draft';x.createdAt=now();draftInv=x;editInv=null;redraw()})}
async function saveInv(st){let d=draftInv;if(!d.clientName)return err('Falta cliente'); if(st!=='draft'&&d.number===nextNo()){d.number=nextNo(); await setPath('settings/next',n(state.settings.next)+1)} d.status=st==='issued'?(n(d.paid)>=invTotals(d).total?'paid':'issued'):st;let t=invTotals(d);Object.assign(d,{subtotal:t.sub,tax:t.tax,total:t.total,pending:t.pending,types:t.types,updatedAt:now()}); await setPath('invoices/'+d.id,d);editInv=null;draftInv=newInv()}
function newPur(){return {id:uid('pur'),date:today(),supplierName:'',supplierId:'',number:'',status:'draft',lines:lines(8),createdAt:now()}}
function purchasesView(){title('Compras'); if(!draftPur)draftPur=newPur(); let t=purTotals(draftPur); $('#view').innerHTML=`<div class="card"><div class="row between"><h3>${editPur?'Editar compra':'Nueva compra'}</h3><div class="row"><button id="newPur" class="btn">Nueva limpia</button><button id="addPur" class="btn">+5 líneas</button><button id="pastePur" class="btn">Pegar pedido/lista</button></div></div><div class="form"><label>Proveedor<input id="pSup" list="supplierList" value="${esc(draftPur.supplierName)}" placeholder="Proveedor"></label><label>Fecha<input id="pDate" type="date" value="${draftPur.date}"></label><label>Nº proveedor<input id="pNo" value="${esc(draftPur.number||'')}"></label><label>Estado<select id="pStatus">${['draft','received','paid','cancelled'].map(s=>`<option ${draftPur.status===s?'selected':''}>${s}</option>`).join('')}</select></label></div><div class="notice" style="margin:12px 0">Compras fácil: busca por código o nombre, escribe completo sin saltos, usa -0,10/+0,10 y al guardar puedes actualizar precios de compra.</div>${lineRows(draftPur,'purchase')}${summary({sub:t.sub,base:t.sub,tax:t.tax,total:t.total})}<div class="row" style="margin-top:12px"><button id="savePur" class="btn primary">Guardar compra</button><button id="savePurCosts" class="btn">Guardar y actualizar costes</button></div></div><div class="card"><h3>Compras guardadas</h3>${table(['Fecha','Proveedor','Nº','Total','Estado','Acciones'],Object.values(state.purchases||{}).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0)).map(p=>{let tt=purTotals(p);return [fd(p.date),esc(p.supplierName),esc(p.number||''),money(tt.total),p.status,`<button class="btn mini" data-open-pur="${p.id}">Editar</button>`]}))}</div>`; bindPurchase()}
function bindPurchase(){let d=draftPur,redraw=purchasesView; $('#newPur').onclick=()=>{editPur=null;draftPur=newPur();redraw()}; $('#addPur').onclick=()=>{for(let i=0;i<5;i++){let l=line();d.lines[l.id]=l}redraw()}; $('#pastePur').onclick=()=>pasteModal('purchase'); ['pSup','pDate','pNo','pStatus'].forEach(id=>$('#'+id).oninput=()=>{let m={pSup:'supplierName',pDate:'date',pNo:'number',pStatus:'status'};d[m[id]]=$('#'+id).value}); bindLines(d,'purchase',redraw); $('#savePur').onclick=()=>savePur(false); $('#savePurCosts').onclick=()=>savePur(true); $$('[data-open-pur]').forEach(b=>b.onclick=()=>{editPur=b.dataset.openPur;draftPur=JSON.parse(JSON.stringify(state.purchases[editPur]));redraw()})}
async function savePur(costs){let d=draftPur,t=purTotals(d);Object.assign(d,{subtotal:t.sub,tax:t.tax,total:t.total,updatedAt:now()});let up={['purchases/'+d.id]:d}; if(costs)Object.values(d.lines).forEach(l=>{if(l.productId){up[`products/${l.productId}/buy`]=n(l.price);up[`products/${l.productId}/updatedAt`]=now()}}); await update(up);draftPur=newPur();editPur=null}
function parseOrder(txt){let out={},client='',tag='';String(txt||'').split(/\n+/).map(x=>x.trim()).filter(Boolean).forEach(raw=>{let lineTxt=raw.replace(/[📦�*]/g,'').trim();let head=lineTxt.match(/pedido\s+(.+)/i); if(head){let p=head[1].split(/[—-]/).map(x=>x.trim());client=p[0]||client;tag=p[1]||tag;return}let m=lineTxt.match(/^(\d+(?:[,.]\d+)?)\s+(.+)$/); if(!m)return;let l=line(),p=findProduct(m[2]);l=p?applyProduct(l,p.code,'',false):{...l,name:m[2].toUpperCase()};l.qty=m[1];out[l.id]=l});return{client,tag,lines:out}}
function ordersView(){title('Pedidos'); if(!draftOrd)draftOrd={id:uid('ord'),date:today(),clientName:'',tag:'',raw:'',lines:{},status:'draft',createdAt:now()}; $('#view').innerHTML=`<div class="card"><h3>Pedidos WhatsApp</h3><div class="form"><label>Cliente<input id="oClient" list="clientList" value="${esc(draftOrd.clientName)}"></label><label>Etiqueta<input id="oTag" value="${esc(draftOrd.tag)}"></label></div><label style="margin-top:10px">Pedido<textarea id="oRaw" rows="8" placeholder="📦 Pedido DANI — LOCUTORIO&#10;2 MV&#10;5 MM&#10;40 CL">${esc(draftOrd.raw)}</textarea></label><div class="row" style="margin-top:10px"><button id="readOrd" class="btn primary">Leer pedido</button><button id="unifyOrd" class="btn">Unificar repetidos</button><button id="ordInv" class="btn">A factura</button><button id="ordPur" class="btn">A compra</button><button id="ordBoth" class="btn">Compra + factura</button><button id="saveOrd" class="btn">Guardar</button></div><div style="margin-top:12px">${table(['Código','Producto','Cantidad','Modo','Compra','Venta','IVA'],Object.values(draftOrd.lines||{}).map(l=>[esc(l.code),esc(l.name),esc(l.qty),l.mode,money(l.buy),money(l.price),l.vat+'%']))}</div></div><div class="card"><h3>Pedidos guardados</h3>${table(['Fecha','Cliente','Etiqueta','Acciones'],Object.values(state.orders||{}).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0)).map(o=>[fd(o.date),esc(o.clientName),esc(o.tag),`<button class="btn mini" data-open-ord="${o.id}">Abrir</button>`]))}</div>`; $('#oClient').oninput=()=>draftOrd.clientName=$('#oClient').value; $('#oTag').oninput=()=>draftOrd.tag=$('#oTag').value; $('#oRaw').oninput=()=>draftOrd.raw=$('#oRaw').value; $('#readOrd').onclick=()=>{let p=parseOrder($('#oRaw').value);draftOrd.clientName=p.client||draftOrd.clientName;draftOrd.tag=p.tag||draftOrd.tag;draftOrd.lines=p.lines;draftOrd.raw=$('#oRaw').value;ordersView()}; $('#unifyOrd').onclick=()=>{let g={};Object.values(draftOrd.lines).forEach(l=>{let k=l.productId||norm(l.name); if(!g[k])g[k]={...l};else g[k].qty=r2(n(g[k].qty)+n(l.qty))});draftOrd.lines={};Object.values(g).forEach(l=>{l.id=uid('l');draftOrd.lines[l.id]=l});ordersView()}; $('#ordInv').onclick=()=>{draftInv=newInv();draftInv.clientName=draftOrd.clientName;draftInv.lines=JSON.parse(JSON.stringify(draftOrd.lines));view='invoices';render()}; $('#ordPur').onclick=()=>{draftPur=newPur();draftPur.lines=JSON.parse(JSON.stringify(draftOrd.lines));Object.values(draftPur.lines).forEach(l=>l.price=l.buy);view='purchases';render()}; $('#ordBoth').onclick=()=>{$('#ordPur').click();setTimeout(()=>{draftInv=newInv();draftInv.clientName=draftOrd.clientName;draftInv.lines=JSON.parse(JSON.stringify(draftOrd.lines))},0)}; $('#saveOrd').onclick=()=>setPath('orders/'+draftOrd.id,draftOrd); $$('[data-open-ord]').forEach(b=>b.onclick=()=>{draftOrd=JSON.parse(JSON.stringify(state.orders[b.dataset.openOrd]));ordersView()})}
function pasteModal(type){openDlg(`<h3>Pegar lista</h3><textarea id="paste" rows="9" placeholder="2 MV&#10;5 MACHO MADURO&#10;40 CL"></textarea><button id="applyPaste" class="btn primary">Aplicar</button>`); $('#applyPaste').onclick=()=>{let p=parseOrder($('#paste').value),doc=type==='invoice'?draftInv:draftPur;doc.lines={...doc.lines,...p.lines}; if(type==='invoice'&&p.client)doc.clientName=p.client; $('#dlg').close(); type==='invoice'?invoicesView():purchasesView()}}
function stockView(){title('Stock');let s=stockCalc();$('#view').innerHTML=`<div class="card"><div class="row between"><h3>Stock</h3><div class="row"><input id="stockSearch" placeholder="Buscar código MV"><button id="toStore" class="btn">Asignar a tienda</button><button id="toWaste" class="btn">Merma</button></div></div>${table(['Código','Producto','Entró','Vendido','Tiendas','Merma','Sobrante','Valor','Detalle'],Object.values(s).sort((a,b)=>a.code.localeCompare(b.code)).map(x=>[`<b>${esc(x.code)}</b>`,esc(x.name),q(x.in),q(x.sold),q(x.store),q(x.waste),`<b>${q(x.qty)}</b>`,money(x.stockValue),`<button class="btn mini" data-st="${x.code}">Ver</button>`]))}</div>`; $('#toStore').onclick=storeForm; $('#toWaste').onclick=wasteForm; $('#stockSearch').oninput=()=>{let c=norm($('#stockSearch').value).replace(/\s/g,''); if(s[c])detailStock(c)}; $$('[data-st]').forEach(b=>b.onclick=()=>detailStock(b.dataset.st))}
function detailStock(c){let x=stockCalc()[c]; if(!x)return; openDlg(`<h3>${esc(x.code)} · ${esc(x.name)}</h3><div class="grid cards">${kpi('Entró',q(x.in))}${kpi('Vendido',q(x.sold))}${kpi('Sobrante',q(x.qty),money(x.stockValue))}${kpi('Coste medio',money(x.avg))}</div><h3>Compras</h3>${table(['Fecha','Proveedor','Cantidad','Precio','Total'],x.purchases.map(a=>[fd(a.date),esc(a.who||''),q(a.qty),money(a.price),money(a.total)]))}<h3>Ventas</h3>${table(['Fecha','Cliente','Factura','Cantidad','Precio','Base'],x.sales.map(a=>[fd(a.date),esc(a.who||''),esc(a.number||''),q(a.qty),money(a.price),money(a.total)]))}`)}
function storeForm(){openDlg(`<h3>Asignar a tienda</h3><div class="form"><label>Tienda<select id="sfStore">${Object.entries(state.stores).map(([id,s])=>`<option value="${id}">${esc(s.name)}</option>`).join('')}</select></label><label>Producto<input id="sfProd" list="productList"></label><label>Cantidad<input id="sfQty" inputmode="decimal"></label><label>Kg/caja<input id="sfKg" inputmode="decimal" placeholder="kg/caja"></label></div><button id="saveSf" class="btn primary">Guardar</button>`); $('#sfProd').onchange=()=>{let p=findProduct($('#sfProd').value);if(p)$('#sfKg').value=p.kgBox||''}; $('#saveSf').onclick=()=>{let p=findProduct($('#sfProd').value);if(!p)return err('Producto no reconocido');let d=productDefaults(p);let l={...line(),productId:p.id,code:p.code,name:p.name,mode:d.mode,kgBox:n($('#sfKg').value)||d.kgBox,qty:$('#sfQty').value,price:d.sell,buy:d.buy,vat:d.vat};let st=$('#sfStore').value,t={id:uid('tr'),date:today(),storeId:st,storeName:state.stores[st].name,lines:{[l.id]:l},createdAt:now()};setPath('storeTransfers/'+t.id,t).then(()=>$('#dlg').close())}}
function wasteForm(){openDlg(`<h3>Registrar merma</h3><div class="form"><label>Motivo<select id="wReason">${['Pasado','Golpeado','Roto','No vendido','Devolución','Regalo','Uso interno','Otro'].map(x=>`<option>${x}</option>`).join('')}</select></label><label>Producto<input id="wProd" list="productList"></label><label>Cantidad<input id="wQty" inputmode="decimal"></label><label>Kg/caja<input id="wKg" inputmode="decimal" placeholder="kg/caja"></label></div><button id="saveW" class="btn primary">Guardar</button>`); $('#wProd').onchange=()=>{let p=findProduct($('#wProd').value);if(p)$('#wKg').value=p.kgBox||''}; $('#saveW').onclick=()=>{let p=findProduct($('#wProd').value);if(!p)return err('Producto no reconocido');let d=productDefaults(p);let l={...line(),productId:p.id,code:p.code,name:p.name,mode:d.mode,kgBox:n($('#wKg').value)||d.kgBox,qty:$('#wQty').value,price:d.buy,buy:d.buy,vat:d.vat};let w={id:uid('w'),date:today(),reason:$('#wReason').value,lines:{[l.id]:l},createdAt:now()};setPath('wastage/'+w.id,w).then(()=>$('#dlg').close())}}
function storesView(){title('Tiendas');$('#view').innerHTML=`<div class="card"><div class="row between"><h3>Tiendas propias</h3><button id="newStoreTr" class="btn primary">+ Traspaso</button></div>${table(['Fecha','Tienda','Líneas'],Object.values(state.storeTransfers||{}).map(t=>[fd(t.date),esc(t.storeName),Object.keys(t.lines||{}).length]))}</div>`; $('#newStoreTr').onclick=storeForm}
function wastageView(){title('Mermas');$('#view').innerHTML=`<div class="card"><div class="row between"><h3>Mermas</h3><button id="newWaste" class="btn primary">+ Merma</button></div>${table(['Fecha','Motivo','Líneas'],Object.values(state.wastage||{}).map(w=>[fd(w.date),esc(w.reason),Object.keys(w.lines||{}).length]))}</div>`; $('#newWaste').onclick=wasteForm}
function productsView(){title('Productos');$('#view').innerHTML=`<div class="card"><div class="row between"><h3>Productos</h3><button id="newProduct" class="btn primary">+ Producto</button></div>${table(['Código','Producto','Modo','Kg/caja','Compra','Venta','Recomendado','IVA','Acciones'],products().map(p=>[esc(p.code),esc(p.name),p.mode,q(p.kgBox),money(p.buy),money(p.sell),money(recPrice(p.buy,p.margin)),p.vat+'%',`<button class="btn mini" data-editp="${p.id}">Editar</button> <button class="btn mini" data-syncp="${p.id}">Sync facturas</button>`]))}</div>`; $('#newProduct').onclick=()=>productForm(); $$('[data-editp]').forEach(b=>b.onclick=()=>productForm(b.dataset.editp)); $$('[data-syncp]').forEach(b=>b.onclick=()=>syncProduct(b.dataset.syncp,true))}
function productForm(pid){let p=pid?state.products[pid]:{code:'',name:'',aliases:[],mode:'kg',kgBox:0,vat:4,buy:0,sell:0,margin:18,unit:'kg',clientMin:{},clientPrice:{}};openDlg(`<h3>${pid?'Editar':'Nuevo'} producto</h3><div class="form"><label>Código<input id="pfCode" value="${esc(p.code)}" placeholder="MV"></label><label>Nombre<input id="pfName" value="${esc(p.name)}"></label><label>Sinónimos<input id="pfAliases" value="${esc((p.aliases||[]).join(', '))}"></label><label>Modo<select id="pfMode">${['kg','box_kg','box_fixed','unit'].map(m=>`<option value="${m}" ${p.mode===m?'selected':''}>${m}</option>`).join('')}</select></label><label>Kg/caja<input id="pfKg" inputmode="decimal" value="${p.kgBox||''}"></label><label>IVA<select id="pfVat">${[0,4,10,21].map(v=>`<option value="${v}" ${n(p.vat)===v?'selected':''}>${v}%</option>`).join('')}</select></label><label>Compra<input id="pfBuy" inputmode="decimal" value="${p.buy||''}"></label><label>Venta<input id="pfSell" inputmode="decimal" value="${p.sell||''}"></label><label>Margen %<input id="pfMargin" inputmode="decimal" value="${p.margin||18}"></label></div><div class="notice">Recomendado: <b id="pfRec">${money(recPrice(p.buy,p.margin))}</b></div><button id="saveP" class="btn primary">Guardar</button>`); ['pfBuy','pfMargin'].forEach(id=>$('#'+id).oninput=()=>$('#pfRec').textContent=money(recPrice($('#pfBuy').value,$('#pfMargin').value))); $('#saveP').onclick=async()=>{let code=$('#pfCode').value.trim().toUpperCase(),name=$('#pfName').value.trim().toUpperCase();if(!code||!name)return err('Código y nombre son obligatorios');let exists=products().find(x=>norm(x.code)===norm(code)&&x.id!==pid);if(exists)return err('Código duplicado');let idp=pid||slug(name);let obj={id:idp,code,name,aliases:$('#pfAliases').value.split(',').map(x=>x.trim()).filter(Boolean),mode:$('#pfMode').value,kgBox:n($('#pfKg').value),vat:n($('#pfVat').value),buy:n($('#pfBuy').value),sell:n($('#pfSell').value),margin:n($('#pfMargin').value),unit:'kg',clientMin:p.clientMin||{},clientPrice:p.clientPrice||{},active:true,updatedAt:now()};await setPath('products/'+idp,obj); if(state.settings.syncProducts)await syncProduct(idp,false,obj); $('#dlg').close()}}
async function syncProduct(pid,notify=false,obj=null){let p=obj||state.products[pid];if(!p)return;let up={},safe=state.settings.protectIssued!==false;function updateLines(doc,path,invoice){let changed=false,lines=JSON.parse(JSON.stringify(doc.lines||{}));Object.values(lines).forEach(l=>{if(l.productId===pid&&!l.manual){let d=productDefaults(p,doc.clientId);l.code=d.code;l.name=d.name;l.mode=d.mode;l.kgBox=d.kgBox;l.vat=d.vat;l.buy=d.buy;l.recommended=d.recommended;l.minClient=d.minClient;l.price=invoice?d.sell:d.buy;changed=true}});if(changed)up[path]=lines}
 Object.values(state.invoices||{}).forEach(i=>{if(safe&&!['draft','reopened'].includes(i.status))return;updateLines(i,'invoices/'+i.id+'/lines',true)});Object.values(state.purchases||{}).forEach(pu=>{if(safe&&!['draft'].includes(pu.status))return;updateLines(pu,'purchases/'+pu.id+'/lines',false)});if(Object.keys(up).length)await update(up); if(notify)openDlg('<div class="notice">Producto sincronizado en borradores/reabiertas.</div>')}
function clientsView(){title('Clientes');$('#view').innerHTML=`<div class="card"><div class="row between"><h3>Clientes</h3><button id="newClient" class="btn primary">+ Cliente</button></div>${table(['Cliente','NIF','Transporte','Comisión','Acciones'],clients().map(c=>[esc(c.name),esc(c.nif),c.transport+'%',c.commission+'%',`<button class="btn mini" data-editc="${c.id}">Editar</button>`]))}</div>`;$('#newClient').onclick=()=>clientForm();$$('[data-editc]').forEach(b=>b.onclick=()=>clientForm(b.dataset.editc))}
function clientForm(cid){let c=cid?state.clients[cid]:{name:'',nif:'',address:'',transport:10,commission:0};openDlg(`<h3>Cliente</h3><div class="form"><label>Nombre<input id="cfName" value="${esc(c.name)}"></label><label>NIF<input id="cfNif" value="${esc(c.nif)}"></label><label>Dirección<input id="cfAddr" value="${esc(c.address)}"></label><label>Transporte %<input id="cfTr" inputmode="decimal" value="${c.transport||0}"></label><label>Comisión %<input id="cfCom" inputmode="decimal" value="${c.commission||0}"></label></div><button id="saveC" class="btn primary">Guardar</button>`);$('#saveC').onclick=()=>{let name=$('#cfName').value.trim();if(!name)return err('Nombre obligatorio');let idc=cid||slug(name);setPath('clients/'+idc,{id:idc,name,nif:$('#cfNif').value,address:$('#cfAddr').value,transport:n($('#cfTr').value),commission:n($('#cfCom').value),active:true}).then(()=>$('#dlg').close())}}
function suppliersView(){title('Proveedores');$('#view').innerHTML=`<div class="card"><div class="row between"><h3>Proveedores</h3><button id="newSup" class="btn primary">+ Proveedor</button></div>${table(['Proveedor','Teléfono'],suppliers().map(s=>[esc(s.name),esc(s.phone||'')]))}</div>`;$('#newSup').onclick=()=>openDlg(`<h3>Proveedor</h3><label>Nombre<input id="sName"></label><label>Teléfono<input id="sPhone"></label><button id="saveS" class="btn primary">Guardar</button>`);setTimeout(()=>{let b=$('#saveS');if(b)b.onclick=()=>{let name=$('#sName').value.trim();if(!name)return;let ids=slug(name);setPath('suppliers/'+ids,{id:ids,name,phone:$('#sPhone').value}).then(()=>$('#dlg').close())}},0)}
function expensesView(){title('Gastos');$('#view').innerHTML=`<div class="card"><div class="row between"><h3>Gastos</h3><button id="newExp" class="btn primary">+ Gasto</button></div>${table(['Fecha','Concepto','Importe'],Object.values(state.expenses||{}).map(e=>[fd(e.date),esc(e.name),money(e.amount)]))}</div>`;$('#newExp').onclick=()=>openDlg(`<h3>Gasto</h3><label>Fecha<input id="eDate" type="date" value="${today()}"></label><label>Concepto<input id="eName"></label><label>Importe<input id="eAmt" inputmode="decimal"></label><button id="saveE" class="btn primary">Guardar</button>`);setTimeout(()=>{let b=$('#saveE');if(b)b.onclick=()=>{let e={id:uid('e'),date:$('#eDate').value,name:$('#eName').value,amount:n($('#eAmt').value)};setPath('expenses/'+e.id,e).then(()=>$('#dlg').close())}},0)}
function paymentsView(){title('Cobros');let rows=Object.values(state.invoices||{}).filter(i=>!['annulled','cancelled'].includes(i.status)).map(i=>{let t=invTotals(i);return [esc(i.clientName),esc(i.number),money(t.total),money(t.paid),money(t.pending),`<button class="btn mini" data-pay="${i.id}">Cobrar</button>`]});$('#view').innerHTML=`<div class="card"><h3>Pendientes y cobros</h3>${table(['Cliente','Factura','Total','Cobrado','Pendiente','Acción'],rows)}</div>`;$$('[data-pay]').forEach(b=>b.onclick=()=>{let inv=state.invoices[b.dataset.pay],t=invTotals(inv);openDlg(`<h3>Cobrar ${esc(inv.number)}</h3><p>Pendiente: <b>${money(t.pending)}</b></p><input id="payAmt" inputmode="decimal" value="${t.pending}"><button id="savePay" class="btn primary">Guardar</button>`);$('#savePay').onclick=()=>{let paid=r2(n(inv.paid)+n($('#payAmt').value));update({['invoices/'+inv.id+'/paid']:paid,['invoices/'+inv.id+'/status']:paid>=t.total?'paid':'partial'}).then(()=>$('#dlg').close())}})}
function reportsView(){title('Informes');let pin=prompt('PIN interno');if(pin!==String(state.settings.pin||'1234')){$('#view').innerHTML='<div class="card"><div class="notice bad">PIN incorrecto.</div></div>';return}let s=stockCalc();$('#view').innerHTML=`<div class="card"><h3>Informe interno</h3><div class="row"><button id="pdfInternal" class="btn primary">PDF interno</button><button id="excel" class="btn">Excel</button></div></div><div class="card">${table(['Código','Producto','Entró','Vendido','Sobrante','Valor'],Object.values(s).map(x=>[x.code,x.name,q(x.in),q(x.sold),q(x.qty),money(x.stockValue)]))}</div>`;$('#pdfInternal').onclick=pdfInternal;$('#excel').onclick=excel}
function settingsView(){title('Ajustes');$('#view').innerHTML=`<div class="card"><h3>Ajustes</h3><div class="form"><label>Nombre<input id="setName" value="${esc(state.settings.name)}"></label><label>PIN<input id="setPin" value="${esc(state.settings.pin)}"></label><label>Prefijo<input id="setPrefix" value="${esc(state.settings.prefix)}"></label><label>Siguiente nº<input id="setNext" inputmode="numeric" value="${state.settings.next}"></label><label>Sync productos en facturas<select id="setSync"><option value="true" ${state.settings.syncProducts!==false?'selected':''}>Sí</option><option value="false" ${state.settings.syncProducts===false?'selected':''}>No</option></select></label><label>Proteger emitidas<select id="setProtect"><option value="true" ${state.settings.protectIssued!==false?'selected':''}>Sí</option><option value="false" ${state.settings.protectIssued===false?'selected':''}>No</option></select></label></div><div class="row" style="margin-top:12px"><button id="saveSet" class="btn primary">Guardar</button><button id="backup" class="btn">Backup JSON</button><button id="clean" class="btn danger">Limpiar ventas y empezar de 0</button></div></div>`;$('#saveSet').onclick=()=>update({'settings/name':$('#setName').value,'settings/pin':$('#setPin').value,'settings/prefix':$('#setPrefix').value,'settings/next':n($('#setNext').value),'settings/syncProducts':$('#setSync').value==='true','settings/protectIssued':$('#setProtect').value==='true'});$('#backup').onclick=backup;$('#clean').onclick=cleanModal}
function cleanModal(){openDlg(`<h3>Limpiar ventas y empezar de 0</h3><div class="notice bad">Conserva productos y clientes. Borra movimientos elegidos.</div><label><input type="checkbox" id="clInv" checked> Facturas</label><label><input type="checkbox" id="clPur" checked> Compras</label><label><input type="checkbox" id="clOrd" checked> Pedidos</label><label><input type="checkbox" id="clStock" checked> Stock, tiendas y mermas</label><label><input type="checkbox" id="clExp" checked> Gastos y cobros</label><label>Escribe LIMPIAR<input id="clText"></label><button id="doClean" class="btn danger">Limpiar</button>`);$('#doClean').onclick=()=>{if($('#clText').value.trim().toUpperCase()!=='LIMPIAR')return err('Confirmación incorrecta');let up={'settings/next':1};if($('#clInv').checked)up.invoices=null;if($('#clPur').checked)up.purchases=null;if($('#clOrd').checked)up.orders=null;if($('#clStock').checked){up.storeTransfers=null;up.wastage=null}if($('#clExp').checked){up.expenses=null;up.payments=null}update(up).then(()=>$('#dlg').close())}}
function pdfInvoice(inv){const {jsPDF}=window.jspdf;let doc=new jsPDF(),t=invTotals(inv);doc.setFont('helvetica','bold');doc.setFontSize(18);doc.text('FACTURA',14,18);doc.setFontSize(10);doc.setFont('helvetica','normal');doc.text('Nº: '+(inv.number||''),14,25);doc.text('Fecha: '+fd(inv.date),14,30);doc.text('IVA aplicado: '+(t.types.length?t.types.join('% / ')+'%':'—'),14,35);doc.setFont('helvetica','bold');doc.text(state.settings.companyName||CFG.companyDefaults.companyName,14,45);doc.setFont('helvetica','normal');doc.text('NIF: '+(state.settings.nif||CFG.companyDefaults.nif),14,50);doc.text(state.settings.address||CFG.companyDefaults.address,14,55);doc.text((state.settings.phone||CFG.companyDefaults.phone)+' · '+(state.settings.email||CFG.companyDefaults.email),14,60);doc.setFont('helvetica','bold');doc.text('Cliente',130,45);doc.setFont('helvetica','normal');doc.text(inv.clientName||'',130,50);let body=Object.values(inv.lines||{}).filter(l=>l.name||l.code).map(l=>{let a=amount(l,false),qty=l.mode==='box_kg'?`${q(l.qty)} cajas x ${q(l.kgBox)} kg = ${q(a.baseQty)} kg`:l.mode==='kg'?`${q(a.baseQty)} kg`:`${q(l.qty)}`;return[l.code||'',l.name||'',qty,money(l.price),money(a.base)]});doc.autoTable({startY:70,head:[['Código','Producto','Cantidad','Precio','Importe']],body,styles:{fontSize:8},headStyles:{fillColor:[20,20,20]}});let y=doc.lastAutoTable.finalY+8;function ln(a,b,bold){doc.setFont('helvetica',bold?'bold':'normal');doc.text(a,130,y);doc.text(b,195,y,{align:'right'});y+=6}ln('Subtotal productos',money(t.sub));if(t.transport)ln('Transporte',money(t.transport));ln('Base imponible',money(t.base));ln('IVA total',money(t.tax));y+=2;doc.roundedRect(128,y-5,70,14,3,3);ln('TOTAL FACTURA',money(t.total),true);ln('Pendiente',money(t.pending));doc.save((inv.number||'factura')+'.pdf')}
function pdfInternal(){const {jsPDF}=window.jspdf;let doc=new jsPDF();doc.text('INFORME INTERNO FACTURA AW',14,18);let s=stockCalc();doc.autoTable({startY:28,head:[['Código','Producto','Entró','Vendido','Sobrante','Valor']],body:Object.values(s).map(x=>[x.code,x.name,q(x.in),q(x.sold),q(x.qty),money(x.stockValue)]),headStyles:{fillColor:[20,20,20]},styles:{fontSize:8}});doc.save('INFORME_INTERNO_'+today()+'.pdf')}
function excel(){let wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(products()),'Productos');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(clients()),'Clientes');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(Object.values(state.invoices||{})),'Facturas');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(Object.values(state.purchases||{})),'Compras');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(Object.values(stockCalc())),'Stock');XLSX.writeFile(wb,'FACTURA_AW_'+today()+'.xlsx')}
function backup(){let blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='FACTURA_AW_BACKUP_'+today()+'.json';a.click();URL.revokeObjectURL(a.href)}
window.addEventListener('DOMContentLoaded',()=>{$('#loginBtn').onclick=()=>fb.auth.signInWithEmailAndPassword($('#email').value.trim(),$('#password').value).catch(e=>$('#loginMsg').textContent=e.message);$('#logout').onclick=()=>fb.auth.signOut();$('#menu').onclick=()=>$('#side').classList.toggle('open');$('#theme').onclick=()=>{let th=document.body.classList.contains('dark')?'light':'dark';state.settings.theme=th;localStorage.setItem('theme',th);setPath('settings/theme',th);applyTheme()};$('#qInv').onclick=()=>{view='invoices';render()};$('#qPur').onclick=()=>{view='purchases';render()};$('#dlgClose').onclick=()=>$('#dlg').close();initFirebase();if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js').catch(()=>{})});
})();
